version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - my_wp_site_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on:
      - db
    image: wordpress:php5.6-apache
    ports:
      - "80:80"
    volumes:
      - my_wp_site_wp_content:/var/www/html/wp-content
      - .:/var/www/html/wp-content/themes/wp-rest-theme/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  my_wp_site_db_data:
    driver: "local"
  my_wp_site_wp_content:
    driver: "local"
